### ISSUE TITLE
building the FacetAnalyzer plugin fails

### ISSUE THREAD

**Issue by carnisj** [romangrothausmann/FacetAnalyser#1]
Dear Roman, 

I am trying to build the FacetAnalyzer plugin on Ubuntu following your PDF available on Researchgate. I encountered no problem when building Paraview (5.7) and ITK (5.0.1) from source, but I get an error with cmake (3.10.2) when trying to build the plugin. I used the required options in cmake (e.g. BUILD SHARED LIBS ON for Paraview) as indicated in the PDF. 
Do I need particular versions of Paraview, ITK and cmake to build the plugin?

![ccmake facet_analyzer](https://user-images.githubusercontent.com/44344327/65716076-b9501a80-e09e-11e9-8daa-59f0cd9f30e4.PNG)
![error lines 32_36](https://user-images.githubusercontent.com/44344327/65716077-b9501a80-e09e-11e9-9ba8-44dff6a552eb.PNG)
![error_ccmake_facet_analyzer](https://user-images.githubusercontent.com/44344327/65716079-b9501a80-e09e-11e9-9ba0-287169c3e991.PNG)

Best regards,

Jerome Carnis

**Comment by romangrothausmann** [comment]
Hi Jerome,

Yes, generally not all combinations of ITK, VTK and PV work well together. The ones you used are possilby to new, especially the changes that came with ITK-5 are not tested for this plug-in. I just checked master and it still works. Master uses VTK from PV-5.2.0

https://github.com/romangrothausmann/FacetAnalyser/blob/189796b0d7532b01af514c4335f5fe6f89338d82/Dockerfile#L42-L43

and ITK-4.12.2

https://github.com/romangrothausmann/FacetAnalyser/blob/189796b0d7532b01af514c4335f5fe6f89338d82/Dockerfile#L60-L61

There is also the PV-5.5.2 branch, which worked end of last year and is currently tested. There used to be this issue:

https://gitlab.kitware.com/paraview/paraview/issues/18454

If you are not bound to built it yourself, you could also try to run PV with the plugin from one of the docker images (https://gitlab.com/romangrothausmann/FacetAnalyser/container_registry).
Sadly, most of them got lost when I re-created the GL project with CI/CD integration to GH. I will try to rebuilt them in the next days.

**Comment by carnisj** [comment]
Hi Roman,
Thank you for the explanations. I made some progress but still run into an error when compiling the plugin. cmake complains that it can not fing vtkPVConfig.h but it is located in the build directory or Paraview (/home/carnisj/paraview_build/). Do you have any idea of how to solve this?
![Compil_error plugin](https://user-images.githubusercontent.com/44344327/65820517-728f2b80-e22a-11e9-809a-1de5b3601019.PNG)
![ccmake plugin](https://user-images.githubusercontent.com/44344327/65820520-77ec7600-e22a-11e9-9f6d-8e6e65e4e004.PNG)

**Comment by romangrothausmann** [comment]
What version of PV have you chosen? I can only see that use ITK-4.12.

**Comment by carnisj** [comment]
Dear Roman,

I use the PV version 5.2.0 that you recommended (git clone --depth 1 -b v5.2.0 https://gitlab.kitware.com/paraview/paraview.git), along with Python2.7 and Qt4 (4.8.7).

Should I try to install VTK separately and use an earlier version of PV?

**Comment by romangrothausmann** [comment]
OK. VTK from PV should be fine. Looking at the configuration for the docker image I could imagine that you need this:
https://github.com/romangrothausmann/FacetAnalyser/blob/189796b0d7532b01af514c4335f5fe6f89338d82/Dockerfile#L97
for your cmake configuration, perhaps also some of the other settings. You could try the whole cmake command line with adjusted paths to your setup.

**Comment by romangrothausmann** [comment]
@carnisj Does it work with `-DCMAKE_CXX_FLAGS="-I/PV_build/"`? If I remove that from the DF, I get the same error as you reported.

**Comment by carnisj** [comment]
Dear Roman,
Now I came up to the point where I try to load the plugin in PV. I get the following message error. The library is located in /itk_build/lib, therefore I suspect that there is one more flag to be set to that path in ccmake, but I could not figure out yet which one it is.
![Screenshot from 2019-10-01 22-02-51](https://user-images.githubusercontent.com/44344327/65996214-4cba8e80-e497-11e9-9933-172cd1520301.png)

**Comment by romangrothausmann** [comment]
Did you set the `*PATH` variables before starting PV? Like in the DF here
https://github.com/romangrothausmann/FacetAnalyser/blob/189796b0d7532b01af514c4335f5fe6f89338d82/Dockerfile#L116-L117
but adjusted to your chosen set-up?

**Comment by carnisj** [comment]
Dear Roman,
Exporting LD_LIBRARY_PATH solved the problem, thank you for your help.

**Comment by romangrothausmann** [comment]
Great to hear you got it working and thanks for your report. Let me know how it goes.
If you need a newer version of PV, try the instructions from the Dockerfile in the pv-5.5.2 branch.
